[package]
name = "twapper"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
secp256k1 = { version = "0.30.0", features = ["rand", "hashes"] }
serde = "1.0.219"
starknet = "0.13.0"
tokio = { version = "1.44.1", features = ["full"] }

[dev-dependencies]
rand = "0.9.0"
